apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: ravi307/backend:v1
    envForm: 
      -ConfigMapRef:
          name:backend
---
kind: Service
apiVersion: v1
metadata:
   name: backend
   namespace: expense
   ports:
   - name: backend-port
     protocol: TCP
     port: 8080
     targetPort: 8080
              